"""updates

Revision ID: 22392a2d9542
Revises: 0d093f837e32
Create Date: 2023-06-29 13:37:43.546618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22392a2d9542'
down_revision = '0d093f837e32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_song_association',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song_association')
    # ### end Alembic commands ###
