"""updates

Revision ID: 608b41be06ea
Revises: 1306f197f7e4
Create Date: 2023-06-30 13:53:59.157535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608b41be06ea'
down_revision = '1306f197f7e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
