"""updates

Revision ID: 79f54cef6778
Revises: f28f37a51b00
Create Date: 2023-06-29 09:10:35.221295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f54cef6778'
down_revision = 'f28f37a51b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
