"""setup

Revision ID: e59a4b99d1b9
Revises: 0b0ddac10cdb
Create Date: 2023-06-28 11:08:09.771157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59a4b99d1b9'
down_revision = '0b0ddac10cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
