"""updates

Revision ID: f200453a45fc
Revises: 79f54cef6778
Create Date: 2023-06-29 09:46:40.242728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f200453a45fc'
down_revision = '79f54cef6778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
