"""updates

Revision ID: f28f37a51b00
Revises: e59a4b99d1b9
Create Date: 2023-06-28 13:30:23.895341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28f37a51b00'
down_revision = 'e59a4b99d1b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    op.drop_column('songs', 'file_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('file_location', sa.VARCHAR(length=255), nullable=True))
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###
